Feature/proxy
corpus-io/dss-vest pull request #28
Opened 2023-05-08 06:57 UTC by malteish

# Motivation and changes
Deploying new instances of DssVest contracts is made cheaper through cloning. 
Cloning requires initializing the clones, which in turn demanded some some changes to the contracts:
- introduction of initializer functions
- creation of clone factories. These were kept small by creating one factory for each type of vesting contract. 

# Caveats
When reviewing this PR, please pay special attention to these questions:
1. Immutability
  a. Does removing the `immutable` flag from variables come with side effects?
  b. Is the github action that counts the assignments to the formerly immutable variables sufficient to remind devs of the security implications of re-assigning these variables?
2. Initializing: Are the initializer functions sufficiently protected? 
3. Memory layout: Inheriting from `Initializable` shifted memory layout. There are tests in place that check on memory layout and needed to be updated. Does this change introduce any vulnerabilities?

# Misc
When calculating coverage, foundry claims DssVestSuckableCloneFactory is not covered. This is[ not true](https://github.com/corpus-io/dss-vest/pull/28/files#diff-5376e79288afcd3ef0fefb9d8fabb7234c111a13c742d492ffdee7d924f5b357R120). I was unable to fix this wrong calculation, so I reduced the coverage requirements slightly.

2023-05-25 08:38 UTC, CJentzsch requested changes

2023-05-25 08:38 UTC, CJentzsch commented on src/DssVest.sol
> +        super.initialize(_ward);
wird die `initialize` function vom DssVest contract nicht schon aufgerufen, weil der Constructor von DssVest ja mit ausgeführt wird?

2023-05-25 08:38 UTC, CJentzsch commented on src/DssVestMintableCloneFactory.sol
> +        return clone;
Would be nice to emit an event logging the new address of the proxy

2023-05-25 09:11 UTC, malteish commented on src/DssVestMintableCloneFactory.sol
> +        return clone;
true [a8adb90](https://github.com/corpus-io/dss-vest/pull/28/commits/a8adb908e3676cfec4c9c61179e605ce79ef25bf)

2023-05-25 09:56 UTC, CJentzsch approved these changes

2023-05-25 09:56 UTC, merged

2026-04-05 15:06 UTC, mankth1993-pixel approved these changes